name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
    - uses: actions/setup-java@v3
    - with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Gradle
      run: ./gradlew.bat build
    - name: Run Tests
      run: ./gradlew.bat test